<?php
/**
 * 스트림 키 관리 API — 구찌야놀자 관리자
 * ref: https://www.php.net/manual/en/function.random-bytes.php
 * ref: https://owasp.org/www-project-secure-headers/
 * ref: https://owasp.org/www-community/attacks/csrf
 */
declare(strict_types=1);

/* ── 세션 시작 */
if (session_status() === PHP_SESSION_NONE) {
    session_set_cookie_params([
        'lifetime' => 0,
        'path'     => '/admin/',
        'domain'   => '',
        'secure'   => true,
        'httponly' => true,
        'samesite' => 'Strict',
    ]);
    session_start();
}

/* ── 보안 헤더 */
if (!headers_sent()) {
    header_remove('X-Powered-By');
    header('Content-Type: application/json; charset=utf-8');
    header('X-Frame-Options: DENY');
    header('X-Content-Type-Options: nosniff');
    header('Cache-Control: no-store, no-cache, must-revalidate');
    header('X-Robots-Tag: noindex, nofollow');
    $https = $_SERVER['HTTPS'] ?? '';
    if ($https !== '' && $https !== 'off') {
        header('Strict-Transport-Security: max-age=31536000; includeSubDomains; preload');
    }
}

error_reporting(0);
ini_set('display_errors', '0');
ini_set('log_errors', '1');

/* ── 관리자 인증 확인 */
$is_admin = !empty($_SESSION['gucci_user'])
    && !empty($_SESSION['gucci_user']['is_admin'])
    && (int)$_SESSION['gucci_user']['is_admin'] === 1;

if (!$is_admin) {
    http_response_code(403);
    echo json_encode(['ok' => false, 'msg' => 'Forbidden'], JSON_UNESCAPED_UNICODE);
    exit;
}

/* ── POST 메서드만 허용 */
$method = $_SERVER['REQUEST_METHOD'] ?? '';
if ($method === 'OPTIONS') {
    http_response_code(200);
    exit;
}
if ($method !== 'POST') {
    http_response_code(405);
    echo json_encode(['ok' => false, 'msg' => 'Method not allowed'], JSON_UNESCAPED_UNICODE);
    exit;
}

/* ── JSON 입력 파싱 */
$raw = (string) file_get_contents('php://input');
if (strlen($raw) > 4096) {
    http_response_code(413);
    echo json_encode(['ok' => false, 'msg' => 'Request too large'], JSON_UNESCAPED_UNICODE);
    exit;
}
$input = json_decode($raw, true);
if (!is_array($input)) {
    http_response_code(400);
    echo json_encode(['ok' => false, 'msg' => 'Invalid JSON'], JSON_UNESCAPED_UNICODE);
    exit;
}

/* ── CSRF 검증
 * ref: https://owasp.org/www-community/attacks/csrf
 */
$csrf = (string)($input['csrf_token'] ?? '');
if (empty($_SESSION['admin_csrf']) || !hash_equals((string)$_SESSION['admin_csrf'], $csrf)) {
    http_response_code(403);
    echo json_encode(['ok' => false, 'msg' => 'CSRF token invalid'], JSON_UNESCAPED_UNICODE);
    exit;
}

$action = (string)($input['action'] ?? '');

switch ($action) {

    case 'regenerate':
        /* 스트림 키 재생성
         * ref: https://www.php.net/manual/en/function.random-bytes.php
         * 정규식: ^sk_live_[a-z0-9]{32}$
         */
        $new_key = 'sk_live_' . bin2hex(random_bytes(16));
        /* 실제 배포 시 DB에 저장 */
        error_log('admin stream-key regenerated by ' . ($_SESSION['gucci_user']['email'] ?? 'unknown'));
        echo json_encode(['ok' => true, 'key' => $new_key], JSON_UNESCAPED_UNICODE);
        break;

    case 'start':
        /* 방송 시작 명령 — 실제 배포 시 SRS API 호출
         * ref: https://ossrs.io/lts/en-us/docs/v6/doc/http-api
         */
        error_log('admin stream START by ' . ($_SESSION['gucci_user']['email'] ?? 'unknown'));
        echo json_encode(['ok' => true, 'msg' => 'Stream start command sent'], JSON_UNESCAPED_UNICODE);
        break;

    case 'stop':
        /* 방송 종료 명령 */
        error_log('admin stream STOP by ' . ($_SESSION['gucci_user']['email'] ?? 'unknown'));
        echo json_encode(['ok' => true, 'msg' => 'Stream stop command sent'], JSON_UNESCAPED_UNICODE);
        break;

    default:
        http_response_code(400);
        echo json_encode(['ok' => false, 'msg' => 'Unknown action'], JSON_UNESCAPED_UNICODE);
}
